STYLE_MAPPINGS = {
    # Front Matter / Preliminary Pages
    "title": "Title",
    "author": "Title Author",
    "institution": "Title Affiliation",
    "course": "Title Course",
    "instructor": "Title Instructor",
    "due_date": "Title Date",
    "registration_number": "Title Registration Number",
    "degree": "Title Degree",
    "title_department": "Title Department",
    "title_byline": "Title Byline",
    "dedication_heading": "Dedication Heading",
    "dedication_body": "Dedication Body",
    "acknowledgements_heading": "Acknowledgement Heading", 
    "acknowledgement_body": "Acknowledgement Body",
    "preface_heading": "Preface Heading",
    "preface_body": "Preface Body",
    "epigraph": "Epigraph",
    "keywords": "Keywords",

    # Key Section Headings
    "abstract_heading": "Abstract Heading", 
    "references_heading": "References Heading",
    "table_of_contents_heading": "Heading 1",
    "appendix_heading": "Appendix Title",
    "appendices_heading": "Appendices Title",
    "heading_1": "Heading 1",
    "heading_2": "Heading 2",
    "heading_3": "Heading 3",
    "heading_4": "Heading 4",
    "heading_5": "Heading 5",

    # Content Types
    "abstract_text": "Abstract",
    "body": "Normal",
    "table_of_contents_item": "Normal",
    "reference_list_item": "References",
    "appendix_text": "Normal",
    "list_item_number": "List Number",
    "list_item_bullet": "List Bullet",
    "list_item_alphabet": "List Alphabet",
    "list_item": "List Item",
    "figure_caption": "Figure Caption",
    "table_caption": "Table Title",
    "table_note": "Table Note",
    "table_data": "Table Body",
    "footnote": "Footnote Text",
    "block_quote": "Block Quote",
    "figure_text": "Normal",
    "code_block": "Code Block",
}
